# Generated by Django 5.0.3 on 2024-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='duration_time',
            field=models.TimeField(verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='periodicity',
            field=models.CharField(default='ежедневно', max_length=50, verbose_name='Периодичность'),
        ),
    ]
